"""changelog.py — Historial de versiones de la aplicación web AROLUZ."""

# Categorías disponibles: "nueva", "mejora", "corrección", "seguridad", "rendimiento"

VERSIONES = [
    {
        "version": "2.9",
        "fecha": "2026-06-03",
        "titulo": "Edición de descripción y precio en carrito sin error de recálculo",
        "cambios": [
            ("corrección", "Editar solo la descripción o el precio de un ítem calculado ya no intenta recalcular — se guarda directamente sin error"),
            ("mejora",     "El recálculo completo (motor) se activa solo cuando se cambia ganancia, espesor o con/sin tapa"),
        ],
    },
    {
        "version": "2.8",
        "fecha": "2026-06-02",
        "titulo": "Selector de rango de fechas en tendencias + simplificación de filtros",
        "cambios": [
            ("mejora",     "Paginación de 3 meses reemplazada por selector de rango libre (fecha desde / hasta) — sin recarga de datos"),
            ("corrección", "Filtros de Tipo eliminados del modal de tendencias (no se usaban)"),
        ],
    },
    {
        "version": "2.7",
        "fecha": "2026-06-02",
        "titulo": "Paginación por período (3 meses) + filtro de precios inválidos",
        "cambios": [
            ("nueva",      "Gráfico de tendencias pagina por ventanas de 3 meses: botones ← Anterior / Siguiente → para navegar entre períodos"),
            ("nueva",      "Etiqueta del período visible con el rango de meses activo (ej: Ene 2026 — Mar 2026)"),
            ("corrección", "Precios iguales a 0 o a 999 (valores centinela/default) se excluyen del gráfico"),
        ],
    },
    {
        "version": "2.6",
        "fecha": "2026-06-02",
        "titulo": "Filtros de espesor y galvanizado en tendencias de precios",
        "cambios": [
            ("nueva",  "Chips de Espesor en el modal de tendencias: 1.2mm / 1.5mm / 2.0mm (incluye equivalencias 1/20 y 1/16)"),
            ("mejora", "Tooltip del gráfico muestra espesor (e=1.5mm) y galvanizado (GO/GC) de cada punto"),
            ("mejora", "Backend extrae espesor de la descripción del ítem y lo filtra en el servidor"),
        ],
    },
    {
        "version": "2.5",
        "fecha": "2026-06-02",
        "titulo": "Corrección crítica: Chart.js bloqueado por CSP",
        "cambios": [
            ("corrección", "Chart.js se cargaba desde cdn.jsdelivr.net, bloqueado por el Content-Security-Policy que solo permite cdnjs.cloudflare.com — cambiado a cdnjs v4.5.0"),
        ],
    },
    {
        "version": "2.4",
        "fecha": "2026-06-02",
        "titulo": "Gráfico de tendencias: enfoque estándar Chart.js responsive",
        "cambios": [
            ("corrección", "Canvas del gráfico ahora usa responsive:true + width/height:100% CSS — el método estándar de Chart.js que funciona independientemente del layout del contenedor"),
            ("corrección", "Dos requestAnimationFrame antes de crear el gráfico, garantizando que el contenedor tenga dimensiones computadas"),
            ("mejora",     "Modal de tendencias con carga lazy: ítems y gráfico solo cargan al seleccionar un cliente, no al abrir el modal"),
            ("corrección", "Si Chart.js no carga desde CDN, se registra el error en consola en lugar de fallar silenciosamente"),
        ],
    },
    {
        "version": "2.3",
        "fecha": "2026-06-02",
        "titulo": "Corrección del gráfico de tendencias de precios",
        "cambios": [
            ("corrección", "Gráfico de tendencias no se renderizaba: canvas recién insertado tenía dimensiones 0×0 al momento de que Chart.js intentaba dibujar"),
            ("corrección", "Eliminada la recreación del canvas en cada render — Chart.js 4 limpia el canvas correctamente con destroy()"),
            ("mejora",     "Canvas dimensionado explícitamente con el tamaño real del contenedor visible antes de crear el gráfico"),
        ],
    },
    {
        "version": "2.2",
        "fecha": "2026-06-02",
        "titulo": "Tendencias de precios por cliente e ítem",
        "cambios": [
            ("nueva",      "Modal 'Estadísticas' del historial reemplazado por gráfico lineal de precio unitario (S/) vs fecha de cotización"),
            ("nueva",      "Panel izquierdo de ítems más cotizados: lista persistente ordenada por frecuencia, clickeable para filtrar el gráfico"),
            ("nueva",      "Búsqueda de ítems con comas (multi-término AND): 'Bandeja, 400x100' filtra ítems que contengan ambas palabras"),
            ("nueva",      "Modo comparación: dos clientes en el mismo gráfico — cliente 1 con línea sólida, cliente 2 con línea discontinua"),
            ("nueva",      "Filtros de chip en el modal: Tipo, Galvanizado, Ganancia y Moneda afectan el gráfico en tiempo real"),
            ("nueva",      "Clic en un punto del gráfico abre el modal 'Ver' de esa cotización específica"),
            ("corrección", "Cotizaciones importadas (pdf_import) ahora se incluyen en tendencias e ítems frecuentes — antes se excluían por filtro de origen"),
            ("corrección", "Gráfico invisible por canvas de tamaño 0: el wrap ahora se muestra antes de que Chart.js renderice"),
            ("mejora",     "Panel de ítems recarga al cambiar el filtro de proyecto"),
            ("mejora",     "Manejo de errores en carga de ítems frecuentes — ya no queda 'Abriendo historial…' congelado si falla el fetch"),
        ],
    },
    {
        "version": "2.1",
        "fecha": "2026-05-29",
        "titulo": "Mejoras de usabilidad móvil en carrito, cotizar y catálogo",
        "cambios": [
            ("mejora",     "Carrito móvil: muestra precio unitario (P.U.) en lugar del precio total por ítem — el total global sigue visible abajo"),
            ("mejora",     "Carrito móvil: nombre completo del ítem sin truncar — se expande en las líneas que necesite"),
            ("mejora",     "Controles de cantidad más anchos en móvil: botones +/− de 32 px y campo de texto de 52 px en el carrito; 44 px y 58 px en Cotizar y Catálogo"),
            ("mejora",     "Al tocar o hacer clic en cualquier campo de cantidad se selecciona el contenido automáticamente — sin borrar manualmente"),
            ("mejora",     "Catálogo: ya no redirige al carrito al agregar un producto — solo muestra un mensaje de confirmación y permite seguir agregando"),
            ("mejora",     "Cantidades enteras se muestran sin decimales innecesarios: '6' en lugar de '6.0', tanto en carga inicial como al usar los botones +/−"),
        ],
    },
    {
        "version": "2.0",
        "fecha": "2026-05-28",
        "titulo": "Gestor de duplicados en importación de PDFs",
        "cambios": [
            ("nueva",      "Modal de importar PDFs reorganizado en dos pestañas: 'Importar PDFs' y 'Gestionar Duplicados'"),
            ("nueva",      "Detección de duplicados durante el parseo: badge 🔁 en la previsualización cuando el PDF ya existe en el historial (mismo cliente + proyecto + total + ítems exactos)"),
            ("nueva",      "Pestaña 'Gestionar Duplicados': agrupa cotizaciones del historial por cliente, proyecto, monto total e ítems idénticos"),
            ("nueva",      "Selección de qué cotizaciones conservar y cuáles eliminar, con validación que impide borrar todo un grupo"),
            ("nueva",      "Botón 'Marcar sugeridos' pre-selecciona los duplicados más antiguos para eliminar con un solo clic"),
            ("nueva",      "Eliminación masiva de duplicados con confirmación explícita (muestra IDs a eliminar)"),
            ("mejora",     "Botón 'Ver' en cada fila del gestor abre el modal de detalle de cotización (no descarga el PDF)"),
            ("mejora",     "Modal de detalle se posiciona por encima del modal de gestión de duplicados al abrirse"),
        ],
    },
    {
        "version": "1.9",
        "fecha": "2026-05-27",
        "titulo": "Precios manuales en el carrito + búsqueda multi-palabra en historial",
        "cambios": [
            ("nueva",      "Precios manuales persistidos en SQLite: editar el precio en el modal lápiz lo guarda como precio_manual y sobrevive a recálculos"),
            ("mejora",     "Indicador visual en el carrito: precio editado manualmente aparece en ámbar con ícono ✎ para distinguirlo de precios calculados"),
            ("nueva",      "Búsqueda por palabras separadas por coma en el historial: '100x100x50, 3/4' filtra cotizaciones donde un mismo ítem contiene AMBAS palabras (no en ítems distintos)"),
            ("mejora",     "Enter en el modal de edición del carrito confirma el guardado (excepto dentro de un textarea sin Ctrl)"),
        ],
    },
    {
        "version": "1.8",
        "fecha": "2026-05-25",
        "titulo": "Drag-and-drop táctil + correcciones de precios en el carrito",
        "cambios": [
            ("nueva",      "Reordenamiento del carrito por drag-and-drop táctil en móviles (long-press + arrastrar)"),
            ("mejora",     "Layout del carrito compacto en mobile con CSS Grid: ítems más legibles en pantallas pequeñas"),
            ("corrección", "Factores de ganancia correctos al recalcular ítems: CH, Curvas V, Tee y Reducción usaban el factor de Bandeja (0.70) en lugar del propio — afectaba separar/juntar tapas y el modal lápiz"),
            ("corrección", "Modal lápiz sobre tapa independiente ahora devuelve el precio de la tapa, no del cuerpo"),
        ],
    },
    {
        "version": "1.7",
        "fecha": "2026-05-21",
        "titulo": "Abreviaciones en clientes + edición avanzada del carrito",
        "cambios": [
            ("nueva",      "Los dropdowns de cliente muestran la abreviación configurada en lugar del código interno (ej: BETONDECKEN en vez de BETONDEC)"),
            ("nueva",      "Lista de Clientes y Atenciones también muestra la abreviación en el panel izquierdo"),
            ("nueva",      "Botones para mover ítems arriba/abajo en la tabla del carrito"),
            ("nueva",      "Recálculo de precio y peso de un ítem con nuevos parámetros (espesor, ganancia, tapa)"),
            ("mejora",     "Editar ítem del carrito actualiza el DOM sin recargar la página"),
            ("mejora",     "Módulo de planchas detecta correctamente ítems combinados (cuerpo + tapa) e ítems en metro lineal"),
        ],
    },
    {
        "version": "1.6",
        "fecha": "2026-05-16",
        "titulo": "Filtros inteligentes de correo + selector de mes",
        "cambios": [
            ("nueva",      "Filtro de 15 patrones de falsos positivos en sync de correo (solicitudes de documentos, consultas, homologaciones, seguimientos, anulaciones, etc.)"),
            ("nueva",      "Selector de mes/año con flechas ‹ › en el modal de sincronizar correo — sin posibilidad de elegir rango arbitrario"),
            ("mejora",     "Límite de emails escaneados ampliado de 80 a 300 por sincronización"),
            ("mejora",     "Tiempo de procesamiento extendido a 110 s para cubrir meses completos con alto volumen"),
        ],
    },
    {
        "version": "1.5",
        "fecha": "2026-05-15",
        "titulo": "Chips de cliente en kanban + mejoras de correo",
        "cambios": [
            ("nueva",      "Chips de cliente visibles en las tarjetas del kanban desde 1 sola obra"),
            ("mejora",     "Dashboard de asistencias con mejoras de visualización"),
            ("corrección", "Error 'Unexpected end of JSON' al sincronizar IMAP con rango largo de fechas"),
        ],
    },
    {
        "version": "1.4",
        "fecha": "2026-05-10",
        "titulo": "Módulo de correo IMAP — sincronización de OCs",
        "cambios": [
            ("nueva",      "Sincronización IMAP: detecta automáticamente correos con OC adjunta (formatos S10, JEF, CLASEM)"),
            ("nueva",      "Parser de PDF de órdenes de compra: extrae número OC, cliente, obra, lugar y fecha de entrega"),
            ("nueva",      "Importación con un clic: crea el proyecto en el kanban con ítems OC cargados"),
            ("nueva",      "Vista previa de PDF del correo antes de importar"),
            ("nueva",      "Geocodificación de dirección de entrega para ordenar ruta Norte→Sur"),
            ("nueva",      "Deduplicación doble: por message-id y por hash SHA-256 del PDF"),
            ("nueva",      "Pestaña 'Correo' en Configuración con presets Gmail / Outlook / Yahoo / Zoho"),
            ("nueva",      "Columnas fecha OC, fecha entrega y lugar en las tarjetas del kanban"),
            ("nueva",      "Notas libres por proyecto en la tarjeta kanban"),
        ],
    },
    {
        "version": "1.3",
        "fecha": "2026-03-20",
        "titulo": "Módulo Asistencias + mejoras mobile",
        "cambios": [
            ("nueva",      "Módulo de asistencias integrado en el mismo servidor (puerto 8000, ruta /asistencias/)"),
            ("nueva",      "Reporte PDF de asistencias generado con WeasyPrint"),
            ("mejora",     "PDF de cotización migrado de ReportLab programático a WeasyPrint + plantilla HTML"),
            ("mejora",     "Scroll fluido, touch targets de 44 px y font-size 16 px anti-zoom en iOS"),
            ("mejora",     "Inputs numéricos/decimales con inputmode correcto en dispositivos móviles"),
            ("corrección", "Cierre automático de sesión por inactividad (10 minutos)"),
        ],
    },
    {
        "version": "1.2",
        "fecha": "2026-03-01",
        "titulo": "Kanban de obras + importar OC desde PDF",
        "cambios": [
            ("nueva",      "Módulo Proyectos Kanban: tablero con columnas COTIZADO / APROBADO / DESPACHADO / ENTREGADO"),
            ("nueva",      "Importar ítems de OC desde PDF (tabla o texto libre, múltiples formatos)"),
            ("nueva",      "Adjuntos por proyecto: PDFs de OC y evidencias de despacho"),
            ("nueva",      "Ruta de despacho: selección de obras y ordenamiento N→S por geocodificación"),
            ("nueva",      "KPIs del pipeline en el home (cotizado, aprobado, despachado, entregado)"),
            ("nueva",      "Compresión automática de imágenes al subir adjuntos"),
            ("nueva",      "CI/CD: auto-deploy a Fly.io en cada push a main"),
            ("mejora",     "Historial con filtros avanzados, ordenamiento y estadísticas"),
            ("mejora",     "Carrito con cantidad decimal y soporte de metro lineal"),
            ("rendimiento","Índices SQLite en cotizaciones, atenciones y email_importados"),
        ],
    },
    {
        "version": "1.1",
        "fecha": "2026-02-15",
        "titulo": "Roles, historial y exportación mejorada",
        "cambios": [
            ("nueva",      "Roles ADMIN / USER: admin ve todo el historial, user solo el propio"),
            ("nueva",      "Página /historial con modal de detalle y exportación PDF/XLSX por cotización guardada"),
            ("nueva",      "Página /clientes con master-detail (RUC, ubicación, email de atención)"),
            ("nueva",      "Página /cuenta: cambio de contraseña para todos los roles"),
            ("nueva",      "Exportación en dólares (USD): conversión automática con la tasa guardada"),
            ("nueva",      "Validez de cotización seleccionable (15 / 30 / 60 / 90 días) en el carrito"),
            ("mejora",     "Header del PDF rediseñado: tabla azul con datos de empresa y subtítulo"),
            ("mejora",     "Carrito persistente en SQLite por usuario (ya no in-memory)"),
        ],
    },
    {
        "version": "1.0",
        "fecha": "2026-02-01",
        "titulo": "Lanzamiento de la versión web",
        "cambios": [
            ("nueva",      "Aplicación web FastAPI accesible desde cualquier dispositivo en la red"),
            ("nueva",      "Motor de cotización web (web/motor.py) con PricingConfig — independiente del desktop"),
            ("nueva",      "Autenticación con cookie firmada (itsdangerous, 7 días de duración)"),
            ("nueva",      "Cotización de los 7 tipos de producto: Bandeja, Curvas H/V, Tee, Cruz, Reducción, Caja de Pase"),
            ("nueva",      "Catálogo de precio fijo"),
            ("nueva",      "Exportación PDF (WeasyPrint) y XLSX (openpyxl) sin dependencia de Excel/Windows"),
            ("nueva",      "Base de datos SQLite auto-creada al primer arranque"),
            ("nueva",      "Deploy en Fly.io con disco persistente para datos y configuración"),
        ],
    },
]
